version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: chatbot_pg_db
    restart: always
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: atminB0s!
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: